from __future__ import annotations

from pathlib import Path
from typing import Any

from echocode.agents.base import BaseAgent
from echocode.utils.files import write_text_file


class CodingAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(name="coding_agent")

    def run(self, payload: dict[str, Any]) -> dict[str, Any]:
        work_item = payload["work_item"]
        allowed_files = work_item.get("allowed_files", [])

        if not allowed_files:
            return {
                "agent": self.name,
                "status": "error",
                "message": "No allowed_files specified.",
            }

        target_file = Path(allowed_files[0])

        code = f'''# Auto-generated by CodingAgent


def execute() -> str:
    return "Work item {work_item["work_item_id"]} executed"
'''

        write_text_file(target_file, code)

        return {
            "agent": self.name,
            "status": "ok",
            "file_written": str(target_file),
        }